### PR TITLE
set up mono_repo configs

### PR DESCRIPTION
**Pull request by jakemac53**
Closes https://github.com/dart-lang/macros/issues/2

I also added tool/dart_model_generator to the workspace config.

### CODE REVIEW

**Comment by davidmorgan** [comment]
Neat, thanks.

`dart_model_generator` doesn't have any test yet, let me see if I can add a golden test... feel free to merge before, to wait, to add an empty test, or to tweak the config so it doesn't test, as you like :)

**Comment by davidmorgan** [comment]
#13 :)

**Review by davidmorgan — APPROVED** [review]

**Review by davidmorgan — APPROVED** [review]

**Comment by jakemac53** [comment]
cc @davidmorgan we are somehow getting carriage returns on windows, I just changed it to use `equalsIgnoringWhitespace` for now, which will only capture meaningful changes... but we could end up swapping between carriage returns and not, if people generate on windows versus other platforms...

**Comment by davidmorgan** [comment]
Curious, maybe add a TODO / issue somewhere? We probably don't want to accidentally publish with different line endings.

**Review by davidmorgan — APPROVED** [review]

**Pull request merged**
